server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlite:file:memdb1?mode=memory&cache=shared
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop  # recreate schema on startup; drop on shutdown
    show-sql: true
    properties:
      hibernate.format_sql: true
